### ISSUE TITLE
alfred 3 에서는 어떻게 설정 할 수 있나요?

### ISSUE THREAD

**Issue by creatorKoo** [eungbean/Alfred-Papago-Workflow#1]
alfred 3 에서는 어떻게 설정 할 수 있나요?

readme에는 지원한다고 기술되어 있지만 자세한 설정 법은 누락되어 있는 것 같습니다.

workflow 설치까지는 했는데 호환되지 않는다고 나오는데 어떻게 하면 사용 할 수 있을지 궁금합니다

**Comment by eungbean** [comment]
최신 맥에서 python2를 더이상 지원하지 않아,
새로이 [python 3기반으로 코드를 다시 작성하여](https://github.com/eungbean/Alfred-Papago-Workflow/releases/tag/v2.0) 릴리즈하였습니다.

한번 테스트해보시고 오류나 불편한 점이 있다면 언제든 말씀해주시면 감사드리겠습니다.
좋은 하루 보내세요!
