### ISSUE TITLE
파파고 사이트에서 번역 결과 보기 기능(ppo)에 대한 사용자 경험을 공유드립니다.

### ISSUE THREAD

**Issue by youngerous** [eungbean/Alfred-Papago-Workflow#2]
안녕하세요? 좋은 워크플로우 만들어주셔서 감사합니다.
다운받은 이후 편리하게 잘 사용하고 있습니다.

다만 ppo 명령어를 사용하면서 개인적으로 느낀 개선점에 대해 공유드리고자 이슈 남깁니다.
pp 명령어의 경우 알프레드 팝업에서 바로 번역 결과를 확인할 수 있지만, ppo는 파파고 웹사이트로 연결되어 번역 결과를 페이지에서 확인할 수 있습니다. 이 과정에서 ppo 명령어가 포함된 **alfred window가 계속 떠 있어 파파고 웹사이트의 번역 결과를 확인하려면 Esc 키를 한 번 더 눌러야 하는 불편함**이 있습니다.

<img width="339" alt="previous" src="https://user-images.githubusercontent.com/38049006/139801241-046684d7-6248-4427-81d4-c9e1379cf1f6.png">

따라서 위의 기존 ppo workflow를 아래와 같이 변경하는 것이 좋지 않을까 제안드립니다.

<img width="367" alt="suggestion" src="https://user-images.githubusercontent.com/38049006/139801317-e89edba0-d971-4245-8ca1-609f5b85da0e.png">

ppo의 목적이 웹사이트에서 보는 것이기 때문에 pp와는 달리 쿼리를 날린 후 alfred window가 바로 닫히는 것이 사용하기에 편리한 것 같습니다. 제안이 합리적이라면 긍정적으로 고려해주시고, 다시 한 번 좋은 워크플로우 제작에 감사의 말씀을 드립니다.

**Comment by eungbean** [comment]
좋은 제안 감사드립니다. 
@youngerous 님의 의견을 반영하여 현재 다음과 같이 workflow를 수정하였습니다.

<img width="367" alt="suggestion" src="https://user-images.githubusercontent.com/38049006/139801317-e89edba0-d971-4245-8ca1-609f5b85da0e.png">

이와 더불어, python3 기반으로 코드를 다시 작성하여 새로이 [릴리즈 (v2.0)](https://github.com/eungbean/Alfred-Papago-Workflow/releases/tag/v2.0) 하였습니다.
한번 테스트해주시고 불편한 점이나 오류가 있다면 제보해주시면 감사드리겠습니다.

다시 한번 감사드립니다.
좋은 하루 보내세요!

**Comment by eungbean** [comment]
추가 업데이트를 진행하였습니다. 
이제 pp 옵션에서 한번에 웹사이트 번역과 복사를 진행할 수 있습니다. 
기존의 ppo는 deprecated 되었습니다 :)
다시한번 감사합니다.
