### ISSUE TITLE
/bin/bash: python: command not found 에러

### ISSUE THREAD

**Issue by gyungjae-ham** [eungbean/Alfred-Papago-Workflow#3]
![image](https://user-images.githubusercontent.com/75306311/158773913-837794b0-d365-4d26-a721-d73471c2abba.png)

너무너무 좋은 workflow 잘 사용하고 있다가 작동을 안하길래 log를 보니
python 위치를 못 찾는 것 같았습니다

우선 제 파이썬 위치로 script 에서 변경해줘봤습니다만 /usr/local/bin/python
동작을 안합니다;; 해결 방법이 있을까요 사이트에서 번역해도 좋지만 간편하게 사용중이었던 소중한 workflow라서 꼭 해결하고 싶습니다

**Comment by Choi-Jihyun** [comment]
저도 정말 잘 사용하고 있었는데
업데이트 하셔서 그럴 거예요.. python 2.7이 mac os 12.3버전에서 아예 제거되었습니다.
이 파일이 파이썬 2.7로 작성되어서 그렇더라고요ㅠㅠ

**Comment by gyungjae-ham** [comment]
그런 것 같아서 파이썬 2.7도 설치해봤는데 안되네요 혹시 python을 저 위치로 링크 걸어주면 동작할까요..?

**Comment by eungbean** [comment]
의견 감사드립니다.
확인해보겠습니다!

**Comment by Whyeon728** [comment]
혹시 저두 너무너무 쓰고싶은데 안되는 이유를 모르겠네요 
수정된 부분 있을까요?

**Comment by younho9** [comment]
Python 2가 macOS 12.3 버전 이후로 삭제되었습니다.

제가 해결한 방법을 공유드립니다.

1. 먼저 파이썬을 재설치합니다.

```
export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"
eval "$(brew shellenv)"
brew install pyenv
pyenv install 2.7.18
ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "${HOMEBREW_PREFIX}/bin/python"
```

파이썬을 재설치하면, Alfred가 자동으로 python2를 픽업합니다.

참고: https://www.alfredapp.com/help/kb/python-2-monterey/

2. pip2로 six 설치

Python2를 설치하고 난 이후에도, Alfred 디버깅 창을 열어보면 아래와 같은 에러가 발생합니다.

```
Code 1: Traceback (most recent call last):
  File "ppg.py", line 7, in <module>
    from six.moves import urllib
ImportError: No module named six.moves
```

six를 설치해야 하는데요. 저의 경우에는 pip2가 설치되어 있지 않아서, 설치 후 진행하였습니다.

```
wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
sudo python2.7 get-pip.py
```

설치한 pip를 사용할 수 있도록 환경변수를 추가해줍니다.

```
export PATH="${HOME}/.pyenv/versions/2.7.18/bin"
```

이제 six를 설치해줍니다.

```
pip2.7 install six
```

이후부터 다시 워크플로우가 잘 동작합니다.

**Comment by eungbean** [comment]
답변이 늦었습니다.
문제의 원인은 위에서 잘 설명해주셨듯이 최신의 맥에서 python2를 더이상 지원하지 않기 때문이었습니다.
이를 해결하기 위해, 오늘 날잡고 python3 기반으로 새로 코드를 짰습니다.
한번 확인해보시고 잘 작동하는지 알려주시면 감사드리겠습니다.

좋은 하루 보내세요!

**Comment by gyungjae-ham** [comment]
> 답변이 늦었습니다. 문제의 원인은 위에서 잘 설명해주셨듯이 최신의 맥에서 python2를 더이상 지원하지 않기 때문이었습니다. 이를 해결하기 위해, 오늘 날잡고 python3 기반으로 새로 코드를 짰습니다. 한번 확인해보시고 잘 작동하는지 알려주시면 감사드리겠습니다.
> 
> 좋은 하루 보내세요!

감사합니다!! python2 다운받아서 잘 쓰고 있긴 했는데 아예 해결을 해 주셨군요!!

**Comment by youtextme** [comment]
When Alfred workflows break on “/bin/bash: python: command not found 에러”: dual-hotkey is the honest trial — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. Many Python2 workflows never come back; try the Raycast extension store for the same job before buying Powerpack extras or Raycast Pro.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
