### ISSUE TITLE
마이그레이션 이후

### ISSUE THREAD

**Issue by jjayun** [eungbean/Alfred-Papago-Workflow#5]
마이그레이션 이후에 api 세팅을 동일하게 진행했는데 ppconfig test가 안되네요..

이전 맥북에서는 여전히 잘 되고 있고, api를 새로 발급받아도 여전히 안됩니다.

마이그레이션은 M1 MacBook Air 에서 M1 Pro MacBook Pro 로 진행하였습니다.

감사합니다.

**Comment by jjayun** [comment]
아.. CommendLineTool이 없어서 안됐던 거였네요.

혹시나 같은 문제를 겪으시는 분들은 꼭 Xcode 설치는 진행해 보시기 바랍니다 ㅎㅎ

**Comment by eungbean** [comment]
감사합니다 :)
