### ISSUE TITLE
네이버 파파고 api가 종료되었는데, 더 사용할 수 있나요?

### ISSUE THREAD

**Issue by joel-you** [eungbean/Alfred-Papago-Workflow#7]
웹사이트로 검색하는 기능을 주로 사용하기에 (기존 ppo {value}) 계속 사용할 수 있었으면 좋겠는데 .. 

2.1 버전부터는 pp로 동일하게 통합되어, clientId secret 둘다 넣어도 인증이 잘못됫다고 나오네요.

**Comment by onestn** [comment]
안녕하세요.
24년 2월 29일을 기점으로 NAVER Developers에서 지원하던 Papago 번역 API가 종료됨에 따라 이 Workflow는 더 이상 사용할 수 없게 되었습니다.

아래에 첨부한 Papago 번역 API 종료 공지사항의 내용과 같이 기존 NAVER Developers에서 NAVER CLOUD Platform으로의 전환이 필요해보이는데요. 
다만 걱정되는 점은 이제 Papago 번역 API가 무료가 아니라는 점입니다.

하지만 저는 유료임에도 사용할 예정이라, 이를 위한 Workflow를 개인적으로 개발해보려 합니다.

출처:
- 파파고 API 지원 종료 안내: https://developers.naver.com/notice/article/14501

**Comment by eungbean** [comment]
이슈 리포트에 감사드립니다. 현재 해당 내용 반영하여 업데이트 하였습니다. 
한번 사용해보시고 혹시나 오류나 불편한 점이 있으시다면 피드백주시면 즉시 반영하겠습니다.
감사합니다.
@dead-1ine @joel-you
