### ISSUE TITLE
client_id/secret 설정이 에러나는거같습니다.

### ISSUE THREAD

**Issue by taese0ng** [eungbean/Alfred-Papago-Workflow#8]
안녕하세요 1.0버전부터 잘사용하고있었는데 며칠전부터 갑자기 404에러가 나서 최신버전으로 업데이트를했습니다.
현재 api쪽 문제인지 client_id/secret을 다시 입력해도 사용을 할 수 없는 것 같습니다 혹시 해당 관련해서 알고계신 이슈인걸까요?

**Comment by taese0ng** [comment]
아 파파고 API가 종료된거군요.. 네이버클라우드로 이관된것같은데 혹시 업데이트 예정있으신가요?

**Comment by taese0ng** [comment]
찾아보니 과금으로 변경됐군요.. 사용이 어려워보입니다 그동안 이용할 수 있어서 좋습니다 감사합니다

**Comment by eungbean** [comment]
@taese0ng 이슈 리포트에 감사드립니다. 현재 해당 내용 반영하여 업데이트 하였습니다.
한번 사용해보시고 혹시나 오류나 불편한 점이 있으시다면 피드백주시면 즉시 반영하겠습니다.
감사합니다.
